name: Build and push a Container image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "*.Dockerfiles"
      - ".github/workflows/build-push.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hotthoughts/devcontainers

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context: [LaTeX, R]
        include:
          - context: LaTeX
            tag: latex-pandoc
          - context: R
            tag: r
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
